### ISSUE TITLE
Text line splitting improvements

### ISSUE THREAD

**Issue by porky11** [femtovg/femtovg#103]
Short list of problems:
- [ ] 1: symbols should belong to words and should not be split from them if possible
- [ ] 2: multiple symbols belong together and should not be split if possible
- [ ] ~3: spaces should be trimmed between split lines~

# Letters and symbols

In the current version of `femtovg` (0.3.5), text line splitting, for example using `canvas.break_text` doesn't work as you would expect.

For example if I have a sentence like this: "Sentence which ends with a dot." And the dot (".") does not fit in the line, while the word "dot" does, it will be split like this:

Line 1: "Sentence which ends with a dot"
Line 2: "."

I would expect it to be like that:

Line 1: "Sentence which ends with a"
Line 2: "dot."

The rule would be, if a letter is followed by a symbol, the symbol still belongs to that word.

# Multiple symbols

Same should be true for a sequence of multiple symbols (like ...).
This would be split into multiple lines as well, if it does not fit in.

For example a line like this "Hello ..."
Might be split into lines like this:

Line 1: "Hello ."
Line 2: ".."

In this case, I would expect this:

Line 1: "Hello"
Line 2: "..."

Combined this means if I have this sentence "He thinks: I would like to go, but..."

It currently could be like this:

Line 1: "He thinks: I would like to go, but.."
Line 2: "."

While it should be like this:

Line 1: "He thinks: I would like to go,"
Line 2: "but..."

# Spaces

Besides that there's a third problem:

If I have multiple words like this split using spaces: "Hello world!"

It could be split like this:

Line 1: "Hello " (see there's still a space after Hello"
Line 2: "World!"

It should rather be split like this:

Line 1: "Hello"
Line 2: "World!"

Else it might cause alignment issues when rendering.

(not sure about this last one. Manual trimming should also be possible, I guess)

**Comment by geom3trik** [comment]
I think I mentioned this before in the Discord but I think one possibility to fix this issue is to use something like this crate <https://github.com/mgeisler/textwrap> with femtovg. The textwrap crate can use unicode breaks, which is a set of rules to determine which characters can be broken and which should stay together when breaking lines.

**Comment by porky11** [comment]
@geom3trik 
I just implemented the rules I mentioned manually.
Wasn't too difficult. I'll push it after I did a bit of testing.

I don't think, textwrap is really suitable. It wraps based on character count and doesn't take in count that characters might not be monospace.
Maybe there is a way to take non monospace characters into account and I just didn't find one yet.
Besides that, it would probably require a huge refactor.
So for now a manual implementation will be a straightforward improvement.

What do you think about automatically removing spaces at line wrap (problem 3)?
Might cause problems when drawing cursors, I guess, so manual trimming is probably the way to go, if you don't want spaces.

In this case, the line "Hello     World!" would be split like this:

```
Hello     
World!
```

(all spaces at the end)

Right?

**Comment by geom3trik** [comment]
> I don't think, textwrap is really suitable. It wraps based on character count and doesn't take in count that characters might not be monospace. Maybe there is a way to take non monospace characters into account and I just didn't find one yet. Besides that, it would probably require a huge refactor. So for now a manual implementation will be a straightforward improvement.

It seems like that at first glance but there's a web demo that shows how to use it with non-monospace fonts. You just need something which can measure the word length, which femtovg provides through `canvas.measure_text`. I've gone and put together a demo of how `textwrap` and `femtovg` could be used together: <https://github.com/geom3trik/femtovg/blob/textwrap/examples/textwrap.rs>.

It's possible to combine them without having to integrate textwrap into femtovg itself but I think a discussion should be had as to whether something like this should be included in femtovg.

> What do you think about automatically removing spaces at line wrap (problem 3)?
Might cause problems when drawing cursors, I guess, so manual trimming is probably the way to go, if you don't want spaces.

I think in vizia we manually trim the spaces but I don't think it matters because it's just for rendering, the underlying text still contains the spaces so that moving the cursor or editing the text still works.
